name: Deploy to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Add config file
        run: echo '${{ secrets.FIREBASE_WEB_CONFIG }}' > ./src/firebase/config.js

      - name: Create service account key file
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > service-account-key.json

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --non-interactive --project triangles-app
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account-key.json

      - name: Clean up credentials
        if: always()
        run: rm -f service-account-key.json
        